### ISSUE TITLE
左侧命令集的刷新按钮是直接重启vscode，能否优化

### ISSUE THREAD

**Issue by BokFang** [SugarTurboS/vscode-beehive-extension#1]
![image](https://user-images.githubusercontent.com/48183966/108847277-7c34e280-761a-11eb-8b2e-cefb464ddf8d.png)
点击刷新时，整个vscode重启了，这个地方能否做个优化，只刷新左侧栏之类的。

**Comment by PDKSophia** [comment]
已解决
